name: Full Stack E2E Deployment

on:
  workflow_dispatch:

jobs:
  infra:
    name: 🚀 Deploy Infraestructura con Terraform
    uses: AgustinAused/infra-repo/.github/workflows/terraform.yml@main
    secrets: inherit

  backend:
    name: 🧠 Deploy Backend Java
    needs: infra
    uses: IgnacioOv/deliverar-pagos-backend/.github/workflows/ci-cd.yml@main
    with:
      alb_dns: ${{ needs.infra.outputs.alb_dns }}
      db_endpoint: ${{ needs.infra.outputs.rds_endpoint }}
    secrets: inherit

  frontend:
    name: 🎨 Deploy Frontend React
    needs: infra
    uses: tu-org/frontend-repo/.github/workflows/deploy.yml@main
    with:
      alb_dns: ${{ needs.infra.outputs.alb_dns }}
      db_endpoint: ${{ needs.infra.outputs.rds_endpoint }}
    secrets: inherit
